CREATE TABLE IF NOT EXISTS "public"."album" (
"id" bigint NOT NULL,
"uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
"title" character varying NOT NULL,
"description" "text" NOT NULL,
"year" numeric NOT NULL,
"profile" bigint NOT NULL,
"created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."album" OWNER TO "postgres";
ALTER TABLE "public"."album" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
SEQUENCE NAME "public"."album_id_seq"
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1
);
ALTER TABLE ONLY "public"."album" ADD CONSTRAINT "album_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."album" ADD CONSTRAINT "album_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profile"("id") ON DELETE CASCADE;