CREATE TABLE IF NOT EXISTS "public"."food" (
"id" bigint NOT NULL,
"uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
"name" character varying NOT NULL,
"profile" bigint NOT NULL,
"created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."food" OWNER TO "postgres";
ALTER TABLE "public"."food" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
SEQUENCE NAME "public"."food_id_seq"
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1
);
ALTER TABLE ONLY "public"."food" ADD CONSTRAINT "food_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."food" ADD CONSTRAINT "food_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profile"("id") ON DELETE CASCADE;