CREATE TABLE IF NOT EXISTS "public"."track" (
"id" bigint NOT NULL,
"uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
"title" character varying NOT NULL,
"artist" character varying NOT NULL,
"album" bigint NOT NULL
);
ALTER TABLE "public"."track" OWNER TO "postgres";
ALTER TABLE "public"."track" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
SEQUENCE NAME "public"."track_id_seq"
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1
);
ALTER TABLE ONLY "public"."track" ADD CONSTRAINT "track_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."track" ADD CONSTRAINT "track_album_fkey" FOREIGN KEY ("album") REFERENCES "public"."album"("id") ON DELETE CASCADE;